// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdbcskaughcwklkhgzaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkYmNza2F1Z2hjd2tsa2hnemF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNDA3ODcsImV4cCI6MjA1ODkxNjc4N30.I-gvjTXXSDCemXl9zwndlRhNYNkv4C5Wk0haP_KQL44";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
