// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsefdvsxnhmeqgwdqwml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzZWZkdnN4bmhtZXFnd2Rxd21sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1MjQ5OTksImV4cCI6MjA1NTEwMDk5OX0.O2a9vAfFUJWlN86_IgjBYUDysI8gOMsmz-f9M9u2C-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);